import { TransaccionModel } from "./transaccion.model";

export class ReservaModel {
    id: number = 0;
    correlativo: number;
    nro_documento: string = "";
    tipo_doc_id: number | null = null;
    nacionalidad_id: number | null = null;
    nombre: string = "";
    primer_apellido: string = "";
    segundo_apellido: string = "";
    estado_civil_id: number | null = null;
    fecha_nacimiento: string = "";
    correo: string = "";
    telefono: string = "";
    cliente_id: number;
    cliente: string = "";
    nombre_corto_cliente: string = "";
    habitacion_id: number;
    grupo_id: number | null = null;
    grupo_nombre: string = "";
    is_grupal: boolean = false;
    habitacion_ids: number[] = [];
    canal_reserva_id: number;
    forma_pago_id: number | null = null;
    forma_pago_servicio_id: number;
    pais_procedencia_id: number;
    estado_reserva_id: number;
    fecha_ini: string = "";
    fecha_fin: string = "";
    detalle: string = "";
    color: string = "";
    cantidad_adulto: number = 1;
    precio_unit_adulto: number = 0;
    cantidad_ninio: number = 0;
    precio_unit_ninio: number = 0;
    tiene_mensaje: boolean = false;
    is_externo: number = 0;
    saldo: number = 0;
    total: number = 0;
    transacciones: TransaccionModel[] = [];
}
